NDefines.NMilitary.PARTICIPATION_SCORE_BLOCKADE = 0.002 -- 0.001
NDefines.NMilitary.PARTICIPATION_SCORE_BATTLE = 0.04 -- 0.03  -- Was 0.05
NDefines.NMilitary.PARTICIPATION_SCORE_SIEGE = 0.01 -- 0.01  - Was 0.02
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 1.4 -- 0.4  -- Was 1.2
NDefines.NMilitary.WARGOAL_MAX_BONUS = 40 -- 25
NDefines.NMilitary.DEFAULT_WARGOAL_WARSCORE_BONUS = 6 -- 5  -- Was 8
NDefines.NMilitary.DEFAULT_WARGOAL_BATTLESCORE_BONUS = 4 -- 3  -- Was 6, which was way too much
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 50 -- 40  -- Was 55
NDefines.NMilitary.NAVAL_DOCTRINE_SAILORS_COST = 0.05			-- Cost for switching naval doctrine (Share of sailors)
NDefines.NReligion.MAX_CHURCH_POWER = 300

-- AI stuff:
NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 1.0 -- Vanilla 1.2
NDefines.NAI.ACCEPTABLE_BALANCE_FRIEND_IN_COMBAT = 0.5 -- Vanilla 0.8
NDefines.NAI.ACCEPTABLE_BALANCE_MULT_OFFENSIVE = 0.5 -- Vanilla 0.85
NDefines.NAI.MIN_CAV_PERCENTAGE = 0 -- Vanilla 5
NDefines.NAI.MAX_CAV_PERCENTAGE = 100 -- Vanilla 50
NDefines.NAI.FOG_OF_WAR_FORGET_CHANCE = 0 -- I wonder how bad it makes AI. Vanilla 1
--NDefines.NAI.FORT_MAINTENANCE_CHEAT = 1 -- Vanilla 0 -- Don't use. Crashes in mp games. MIGHT WORK NOW?
NDefines.NAI.PS_SHORT_TERM_POOL = 0 -- Vanilla 100
NDefines.NAI.AGGRESSIVENESS = 10000 -- Vanilla 200
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 10000 -- Vanilla 300
NDefines.NAI.MISSION_PICK_CHANCE = 100 -- Vanilla 33
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 0 -- Vanilla 6
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS_PEACETIME = 0 -- Vanilla 48
--NDefines.NAI.ARTILLERY_FRACTION = 0.25 -- Vanilla 0.35 # Set to same in vanilla now
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 7 -- Vanilla 11
NDefines.NAI.TRANSPORT_FRACTION = 0.1 -- Vanilla 0.5
NDefines.NAI.INCOME_SAVINGS_FRACTION = 0 -- Vanilla 0.25
NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 0.1 -- Vanilla 10
NDefines.NAI.DESIRED_SURPLUS = 0 -- Vanilla 0.1
NDefines.NAI.DESIRED_DEFICIT = 0 -- Vanilla 0.01
NDefines.NAI.EXTRA_SURPLUS_WHEN_NEEDING_BUILDINGS = 0 -- Vanilla 0.15
NDefines.NAI.MAX_SAVINGS = 0 -- Vanilla 60
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MAX = 0.9 -- Vanilla 0.35
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MIN = 0.3 -- Vanilla 0.15
NDefines.NAI.STATE_MAINTENANCE_BUDGET_FRACTION = 0.1 -- Vanilla 0.15
NDefines.NAI.ARMY_BUDGET_FRACTION = 2.0 -- Vanilla 0.6
NDefines.NAI.NAVY_BUDGET_FRACTION = 0.1 -- Vanilla 0.3
NDefines.NAI.FORT_BUDGET_FRACTION = 0.2 -- Vanilla 0.3
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 1000 -- Vanilla 100
NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 1 -- Vanilla 100
NDefines.NAI.CALL_IN_ALLIES_POWER_RATIO = 100.0 -- Vanilla 4.0
NDefines.NAI.DANGEROUS_OVEREXTENSION_PERCENTAGE = 1.0 -- Vanilla 0.1

NDefines.NAI.DEBASE_THRESHOLD = 0 -- Vanilla 10000
NDefines.NAI.DEVELOPMENT_CAP_BASE = 33 -- Vanilla 10
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_THRESHOLD = 20 -- Vanilla 10
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_FACTOR = 0 -- Vanilla 2.0

NDefines.NAI.ADVISOR_MIN_SKILL_RELUCTANT_FIRE = 1 -- Vanilla 3
NDefines.NAI.FIRE_ADVISOR_LOAN_REQUIREMENT = 9 -- Vanilla 5
NDefines.NAI.BUY_INDULGENCE_BASE_AI_DESIRE = 0 -- Vanilla 0.5
NDefines.NAI.BUY_INDULGENCE_RIVAL_AI_DESIRE = 0 -- Vanilla 1
NDefines.NAI.BUY_INDULGENCE_EXCOM_AI_DESIRE = 0 -- Vanilla 10
NDefines.NAI.RECRUIT_ADVISOR_BASE_AI_DESIRE = 1000.0 -- Vanilla 10.0
NDefines.NAI.PROMOTE_ADVISOR_BASE_AI_DESIRE = 1000.0 -- Vanilla 10.0
NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 1.0 -- Vanilla 5.0
NDefines.NAI.ESTATE_MAX_WANTED_INFLUENCE = 90.0 -- Vanilla 73.0
NDefines.NAI.ESTATE_MIN_WANTED_CROWNLAND = 10.0 -- Vanilla 33.0

NDefines.NAI.COLONY_BUDGET_FRACTION = 1 -- Vanilla 0.4

NDefines.NAIEconomy.MILITARY_FOCUS_DEFAULT = 2.0 -- Vanilla 1.0
NDefines.NAIEconomy.MILITARY_FOCUS_LOWER_BOUND = 2.0 -- Vanilla 0.0
NDefines.NAIEconomy.MILITARY_FOCUS_UPPER_BOUND = 4.0 -- Vanilla 1.5
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIZE = 2.0 -- Vanilla 1.5
NDefines.NAIEconomy.ARMY_FRACTION_PEACEFUL = 1.0 -- Vanilla 0.9
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIST = 2.0 -- Vanilla 1.25
NDefines.NAIEconomy.FORT_FRACTION_MILITARIZE = 2.0 -- Vanilla 1.33
NDefines.NAIEconomy.FORT_FRACTION_MILITARIST = 2.0 -- Vanilla 1.25
NDefines.NAIEconomy.FORT_FRACTION_CAPITALIST = 2.0 -- Vanilla 0.8
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY_WARTIME = 0 -- Vanilla 0.5

NDefines.NAI.DEVELOPMENT_CAP_BASE = 30    -- AI will not develop provinces that have more development than this or DEVELOPMENT_CAP_MULT*original development (whichever is bigger)
NDefines.NAI.DEVELOPMENT_CAP_MULT = 1.2

NDefines.NMilitary.NOMAD_PLAINS_SHOCK_BONUS = 0.15
NDefines.NMilitary.NOMAD_NON_PLAINS_SHOCK_PENALTY = -0.15

NDefines.NGovernment.GOVERNMENT_REFORM_COST_CENTRALIZE_STATE = 0
NDefines.NGovernment.CENTRALIZE_STATE_ADM_COST = 100
